### PR TITLE
Clarify the Ansible playbook

### PR DESCRIPTION
**Pull request by leseb**
I tried to clarify and simplify the Ansible playbook by adding variables
sticked to Distribution, loops and more variables in general.

I cannot test this so hopefully I did not break to much things :).

@fredericlepied this is just for you!

Signed-off-by: Sébastien Han <sebastien.han@enovance.com>

### CODE REVIEW

**Comment by leseb** [comment]
@fredericlepied not sure if the vars directories will work as expected due to the structure of the directory itself, let's see if it works like this. If not it might be better to move deeply-ansible to its own repo :)

**Comment by leseb** [comment]
@fredericlepied I broke a couple of things, testing and fixing at the moment.

**Comment by leseb** [comment]
@fredericlepied works for me :)

**Comment by fredericlepied** [comment]
Thx @leseb !

**Pull request merged**
